GMAIL_EMAIL: 'volo.lead@gmail.com'
GMAIL_PASSWORD: 'volovolo2017'

SENDINBLUE_EMAIL: 'volo.lead@gmail.com'
SENDINBLUE_PASSWORD: '1kRxpzJQrC0vTh7Z'

AWS_ID: 'AKIAIZMPVBAIABLHP7PA'
AWS_SECRET: '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'
