GMAIL_EMAIL: 'volo.lead@gmail.com'
GMAIL_PASSWORD: 'volovolo2017'

SENDINBLUE_EMAIL: 'volo.lead@gmail.com'
SENDINBLUE_PASSWORD: '1kRxpzJQrC0vTh7Z'

AWS_ACCESS_KEY_ID: 'AKIAIZMPVBAIABLHP7PA'
AWS_SECRET_ACCESS_KEY: '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'
AWS_REGION: 'ca-central-1'
S3_BUCKET_NAME: 'volo-avatar'
